name: serpro_integra_contador_api
description: Package Dart para acessar a API do SERPRO Integra Contador.
version: 1.0.4
homepage: https://github.com/MarlonSantosDev/serpro_integra_contador_api

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  http: ^1.6.0

dev_dependencies:
  test: ^1.24.3

