name: serpro_integra_contador_api
description: Package Dart para acessar a API do SERPRO Integra Contador.
version: 1.1.0
homepage: https://github.com/MarlonSantosDev/serpro_integra_contador_api

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  http: ^1.6.0
  pointycastle: ^3.9.1  # Assinatura RSA-SHA256
  asn1lib: ^1.6.5       # Análise PKCS12
  xml: ^6.5.0           # Manipulação XML
  crypto: ^3.0.7        # Hash SHA-256

dev_dependencies:
  test: ^1.28.0

